version: '3.4'

services:
  test_server:
    command: /test-server
    build:
      context: "."
      dockerfile: Dockerfile
      target: test_server
    ports:
      - "8080:8080"

  server:
    command: /grpc-example
    build:
      context: "."
      dockerfile: Dockerfile
      target: main
    ports:
      - "7532:7532"
    depends_on:
      - test_server
    links:
      - test_server

  client:
    #command: /grpc-example server:7532 http://dl-cdn.alpinelinux.org/alpine/v3.11/releases/aarch64/alpine-minirootfs-3.11.6-aarch64.tar.gz
    command: /grpc-example server:7532 http://test_server:8080/blob.tar.gz
    build:
      context: "."
      dockerfile: Dockerfile
      target: main
    volumes:
      - tmp:/tmp
    depends_on:
      - server
    links:
      - server


volumes:
  tmp:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $PWD/tmp
