version: '3.4'

services:
  test_server:
    command: /test-server
    working_dir: /
    build:
      context: "."
      dockerfile: Dockerfile-App
      target: test_server
    ports:
      - "8080:8080"

  test_runner:
    command: go test -v .
    working_dir: /src
    build:
      context: "."
      dockerfile: Dockerfile-App
      target: test_server
    depends_on:
      - test_server
    links:
      - test_server
