version: '3.4'

services:
  test_server:
    command: /test-server
    working_dir: /
    image: docker.pkg.github.com/thearchitect/grpc-example/actions:latest
    ports:
      - "8080:8080"

  test_runner:
    command: go test -v -benchmem -bench=. .
    working_dir: /src
    image: docker.pkg.github.com/thearchitect/grpc-example/actions:latest
    depends_on:
      - test_server
    links:
      - test_server
