#!/usr/bin/env bash
set -e -x

docker build -f Dockerfile-Base --target prepared -t docker.pkg.github.com/thearchitect/grpc-example/actions:latest .
docker push docker.pkg.github.com/thearchitect/grpc-example/actions:latest

# TODO --squash
