#!/usr/bin/env bash
set -e -x

docker build --target test_server -t docker.pkg.github.com/thearchitect/grpc-example/actions:latest .
docker push docker.pkg.github.com/thearchitect/grpc-example/actions:latest

# TODO --squash
